swagger: "2.0"
info:
  version: "0.0.1"
  title: bdx-quizz
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /
# 
tags:
  - name: users
    description: Logged in user
  - name: visitor
    description: Operations available to non account user
    
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /categories:
    get:
      tags:
        - visitor
      description: Returns the categories lists
      operationId: categoriesList
      responses:
        "200":
          description: Sucess

  
  /users:
    get:
      tags:
        - "users"
      description: Returns the users list
      # used as the method name of the controller
      operationId: usersList
      responses:
        "200":
          description: Sucess
  /user:
    post:
      tags:
        - visitor
      description: Create a new user 

      responses:
        "200":
          description: Sucess


  /topPlayers:
    get:
      tags:
      - visitor
      description: Returns the top 3 users of all categories
      responses:
        "200":
          description: Sucess

  /topPlayers/{categoryId}:
    get:
      tags:
        - visitor
      description: Returns the top 3 users of a specified category
      responses:
        "200":
          description: Sucess

  
  /question/{categoryId}/random:
    get:
      tags:
        - users
      description: Returns a random question.
      responses:
        "200":
          description: Success
          
  /question/{categoryId}/{difficultyId}/random:
    get:
      tags:
        - users
      description: Return a random question with the selected difficulty and category.
      responses:
        "200":
          description: Success
  
  /response/{questionId}:
    get:
      tags:
        - users
      description:
        Returns the response of a specified question
      responses:
        "200":
          description: Success
  
  /user/{playerId}:
    get:
      tags:
        - users
      description: Return the profile of a specified player
      responses:
        "200":
          description: Success
          
  /user/{playerId}/invite:
    post:
      tags:
        - users
      description: Send friend request to a user
      responses:
        "200":
          description: Success
      
        
  
    
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  HelloWorldResponse:
    required:
      - message
    properties:
      message:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
        